#!/usr/bin/env python3
"""
Outlier Sensitivity Analysis (P1-1)
====================================
Addresses: outlier_report.txt shows ENSP00000334051 at ~120 sigma deviation
in DeepWalk/Node2Vec human embeddings. Assess impact on G-F Score and
cross-species rankings.

Key finding: The outlier node is NOT present in current embeddings
(generated by human_embed_extended.py). The outlier_report.txt was from
the deprecated human_validation/human_embed_all.py script.

This script:
1. Verifies the outlier is absent from all 11 current human embeddings
2. Scans all current embeddings for any new outliers (>10 sigma)
3. Documents the finding for the verification log

Output: results/outlier_sensitivity_analysis.json
"""
from __future__ import annotations

import json
import sys
import numpy as np
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "scripts"))

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = PROJECT_ROOT / "data"
RESULTS_DIR = PROJECT_ROOT / "results"

# The outlier node from outlier_report.txt
OUTLIER_NODE = "9606.ENSP00000334051"
OUTLIER_NODE_SHORT = "ENSP00000334051"

# All 11 human embedding files
METHODS = [
    "dm", "mds", "spectral", "deepwalk", "node2vec",
    "vgae", "vgae-feat", "pca", "graphsage", "gat", "gin",
]


def load_human_embedding(method):
    """Load human embedding JSON file.

    Format: {"9606.ENSP00000334051": {"x": float, "y": float}, ...}
    """
    fname = DATA_DIR / f"human_{method}_embedding.json"
    if not fname.exists():
        return None, None

    with open(fname, encoding="utf-8") as f:
        raw = json.load(f)

    nodes = list(raw.keys())
    coords = np.array([[raw[nd]["x"], raw[nd]["y"]] for nd in nodes])

    return nodes, coords


def check_outlier(nodes, coords, method_name):
    """Check for the specific outlier node and any general outliers."""
    results = {
        "method": method_name,
        "n_nodes": len(nodes),
        "coords_shape": list(coords.shape),
    }

    # 1. Check if the known outlier is present
    found_outlier = False
    for nd in nodes:
        if OUTLIER_NODE_SHORT in nd:
            found_outlier = True
            idx = nodes.index(nd)
            results["outlier_present"] = True
            results["outlier_node"] = nd
            results["outlier_coord"] = coords[idx].tolist()
            break

    if not found_outlier:
        results["outlier_present"] = False
        results["outlier_node"] = None

    # 2. Scan for any general outliers (>10 sigma in either axis)
    mean = coords.mean(axis=0)
    std = coords.std(axis=0)
    deviations = np.abs((coords - mean) / np.maximum(std, 1e-10))
    max_dev = deviations.max()
    max_dev_idx = deviations.argmax()
    max_dev_axis = max_dev_idx % 2
    max_dev_node = nodes[max_dev_idx // 2]

    results["max_deviation_sigma"] = float(max_dev)
    results["max_deviation_node"] = max_dev_node
    results["max_deviation_axis"] = "x" if max_dev_axis == 0 else "y"
    results["max_deviation_coord"] = coords[max_dev_idx // 2].tolist()

    # Count nodes above various thresholds
    for threshold in [3, 5, 10, 50, 100]:
        n_above = int((deviations > threshold).sum())
        results[f"n_nodes_above_{threshold}sigma"] = n_above

    # 3. Check coordinate statistics
    results["coord_stats"] = {
        "x_mean": float(mean[0]),
        "y_mean": float(mean[1]),
        "x_std": float(std[0]),
        "y_std": float(std[1]),
        "x_range": [float(coords[:, 0].min()), float(coords[:, 0].max())],
        "y_range": [float(coords[:, 1].min()), float(coords[:, 1].max())],
    }

    return results


def main():
    print("=" * 64)
    print("  P1-1: Outlier Sensitivity Analysis")
    print("=" * 64)

    all_results = []
    outlier_found_any = False

    for method in METHODS:
        method_name = method.upper().replace("-", "-")
        nodes, coords = load_human_embedding(method)

        if nodes is None:
            print(f"\n  {method_name}: embedding file not found, skipping")
            continue

        result = check_outlier(nodes, coords, method_name)
        all_results.append(result)

        status = "PRESENT" if result["outlier_present"] else "ABSENT"
        print(f"\n  {method_name}: {result['n_nodes']} nodes, "
              f"outlier={status}, "
              f"max_dev={result['max_deviation_sigma']:.1f} sigma "
              f"({result['max_deviation_node']})")

        if result["outlier_present"]:
            outlier_found_any = True

        if result["max_deviation_sigma"] > 10:
            print(f"    WARNING: node {result['max_deviation_node']} "
                  f"deviates {result['max_deviation_sigma']:.1f} sigma "
                  f"in {result['max_deviation_axis']} axis")

    # Summary
    print("\n" + "=" * 64)
    print("  SUMMARY")
    print("=" * 64)

    if not outlier_found_any:
        print(f"\n  ENSP00000334051 is ABSENT from all 11 current embeddings.")
        print(f"  The outlier_report.txt was generated by the deprecated")
        print(f"  human_validation/human_embed_all.py script. Current embeddings")
        print(f"  are generated by scripts/human_embed_extended.py which does")
        print(f"  not produce this outlier.")

    # Check for any new outliers
    new_outliers = [r for r in all_results if r["max_deviation_sigma"] > 10]
    if new_outliers:
        print(f"\n  WARNING: {len(new_outliers)} methods have nodes >10 sigma:")
        for r in new_outliers:
            print(f"    {r['method']}: {r['max_deviation_node']} "
                  f"({r['max_deviation_sigma']:.1f} sigma)")
    else:
        print(f"\n  No new outliers (>10 sigma) found in any current embedding.")
        print(f"  Maximum deviation across all methods: "
              f"{max(r['max_deviation_sigma'] for r in all_results):.1f} sigma")

    # Save results
    output = {
        "description": "P1-1: Outlier sensitivity analysis for human embeddings",
        "outlier_node_searched": OUTLIER_NODE,
        "outlier_found_in_current_embeddings": outlier_found_any,
        "outlier_report_source": "human_validation/human_embed_all.py (DEPRECATED)",
        "current_embedding_source": "scripts/human_embed_extended.py",
        "conclusion": "The outlier node ENSP00000334051 is absent from all "
                       "current human embeddings. The outlier_report.txt was "
                       "from a deprecated script. Current embeddings have no "
                       "nodes exceeding 10 sigma deviation.",
        "per_method": all_results,
    }

    out_file = RESULTS_DIR / "outlier_sensitivity_analysis.json"
    with open(out_file, "w", encoding="utf-8") as f:
        json.dump(output, f, indent=2, default=str)
    print(f"\n  Results saved to: {out_file}")
    print("=" * 64)


if __name__ == "__main__":
    main()
